---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: ci
- name: linux-rc

outputs:
- name: resource-versions

run:
  path: ci/tasks/scripts/build-release-resource-versions

